version: '3.6'

networks :
   alexgochain:

services:
 go:
   image: 'gochain'
   build: .
   ports: 
     - '8000:8000'
   networks: 
     - 'alexgochain'
   depends_on:
     - 'postgres'

 postgres:
   image: "postgres"
   environment:
     - 'POSTGRES_PASSWORD=1A2B3456789'
   networks: 
     - 'alexgochain'
   ports: 
     - '5432:5432'
